// Writes docs/ECONOMY.md: every formula of the upgrade economy, explained per sport, with numbers taken from the real
// game code (so the document cannot drift from the game). Usage: npm run docs:economy
import { writeFileSync } from 'node:fs';
import { BALANCE, LEVEL_MILESTONES, STATS, STAT_IDS, costFactor, milestoneMult, tierFactor, type StatId } from '../src/config/balance';
import { EXPANSIONS, EXPANSION_MULT } from '../src/config/expansions';
import { FACILITIES } from '../src/config/facilities';
import { SPORTS, ZONES, type ZoneRef } from '../src/config/sports';
import { costOf, managerCost, statCost, zoneStats } from '../src/core/economy';
import { newGame, newZone } from '../src/core/state';
import { simulate } from '../src/core/bot';

const state = newGame(0);
state.skills = {}; // no free root skills: the pure formulas only
const ONE = { coins: 1, speed: 1 };

const SUFFIX = ['', 'K', 'M', 'B', 'T', 'Qa', 'Qi', 'Sx', 'Sp', 'Oc', 'No', 'Dc'];
function f(n: number): string {
  if (!isFinite(n)) return '-';
  if (n >= 1e36) return n.toExponential(2).replace('e+', ' x 10^');
  if (n < 1000) return n < 10 ? String(Math.round(n * 100) / 100) : String(Math.round(n * 10) / 10);
  const e = Math.min(SUFFIX.length - 1, Math.floor(Math.log10(n) / 3));
  const v = n / 10 ** (e * 3);
  return `${v < 10 ? v.toFixed(2) : v < 100 ? v.toFixed(1) : v.toFixed(0)}${SUFFIX[e]}`;
}
function t(sec: number): string {
  if (!isFinite(sec)) return '-';
  if (sec < 90) return `${Math.round(sec * 10) / 10} s`;
  if (sec < 5400) return `${Math.round(sec / 6) / 10} min`;
  if (sec < 172800) return `${Math.round(sec / 360) / 10} h`;
  if (sec < 86400 * 365) return `${Math.round(sec / 8640) / 10} days`;
  return `${(sec / (86400 * 365)).toExponential(1)} years`;
}

type Lv = { capacity: number; price: number; speed: number };
function stats(ref: ZoneRef, lv: Lv) {
  const z = { ...newZone(true), ...lv };
  return zoneStats(state, ref, z, ONE);
}
const ZERO: Lv = { capacity: 0, price: 0, speed: 0 };
const withStat = (stat: StatId, n: number): Lv => ({ ...ZERO, [stat]: n });

const CHECK: Record<StatId, number[]> = {
  price: [10, 25, 50, 100, 200, 500, 1000],
  capacity: [5, 10, 25, 50, 100],
  speed: [10, 25, 50, 100],
};
const LABEL: Record<StatId, string> = { price: 'Level up (price per guest)', capacity: 'Bigger class (guests)', speed: 'Faster turnover (session time)' };

const out: string[] = [];
const p = (s = '') => out.push(s);

p('# Surf Tycoon - the upgrade economy, per sport');
p();
p('Generated by `npm run docs:economy` (`scripts/economy-doc.ts`) from the real game code: every number below is computed by the same functions the game uses (`src/core/economy.ts`, `src/config/balance.ts`, `src/config/sports.ts`). Change a balance number, run the script, and this file is correct again. Nothing in the game is random, so all of this is exact.');
p();
p('All coins/second figures assume a **managed** zone (it restarts by itself) and **no skills, no beach buildings, no ad boost, no expansion multiplier**: the pure upgrade maths. Multipliers are described in section 5 and simply multiply the result.');
p();

// ---------------------------------------------------------------- 1
p('## 1. The formulas');
p();
p('Every zone (a "level" of a sport: 6 sports x 4 levels = 24 zones) has three bought stats, each with its own level counter: **price** (Level up), **capacity** (Bigger class), **speed** (Faster turnover). A zone also has fixed data: `tier`, `baseGuests`, `baseSeconds`.');
p();
p('### Income of a zone');
p('```');
p('guests          = baseGuests + capacity                    (+ skill guests)');
p('pricePerGuest   = tierScale^tier x (1 + priceStep x price) x milestoneMult(price) x coinMultiplier');
p('duration        = baseSeconds / ((1 + speedStep x speed) x speedMultiplier)');
p('incomePerSession = guests x pricePerGuest');
p('coinsPerSecond   = incomePerSession / duration');
p('```');
p(`with tierScale = **${BALANCE.tierScale}**, priceStep = **${BALANCE.priceStep}** (each Level up adds +5% of the *base* price, i.e. linear, not compounding), speedStep = **${BALANCE.speedStep}** (each Faster turnover adds +2% of base speed).`);
p();
p('So the three stats are **multiplicative with each other** but each one is **linear in its own level**:');
p('`coinsPerSecond = tierScale^tier x (baseGuests + capacity) x (1 + 0.05 x price) x milestoneMult(price) x (1 + 0.02 x speed) / baseSeconds`');
p();
p('### Cost of an upgrade');
p('```');
p('cost(stat, level) = baseCost(stat) x costScale^tier x growth(stat)^level x (1 + surge(stat) x level) x (1 - discount)');
p('```');
p(`costScale = **${BALANCE.costScale}** (bigger than tierScale = ${BALANCE.tierScale} on purpose: each tier earns ${BALANCE.tierScale}x more but costs ${BALANCE.costScale}x more, so higher tiers are slower to climb, a factor ${(BALANCE.costScale / BALANCE.tierScale).toFixed(2)} per tier). \`level\` is the number already bought, so the first purchase uses level 0. Discounts come from skills and are capped at 70%.`);
p();
p('| stat | UI name | baseCost | growth (per level) | surge | max level | effect of one level |');
p('|---|---|---|---|---|---|---|');
p(`| price | Level up | ${STATS.price.baseCost} | x${STATS.price.growth} | ${STATS.price.surge} | ${STATS.price.max} | +${BALANCE.priceStep * 100}% of base price per guest (linear) |`);
p(`| capacity | Bigger class | ${STATS.capacity.baseCost} | x${STATS.capacity.growth} | ${STATS.capacity.surge} | ${STATS.capacity.max} | +1 guest |`);
p(`| speed | Faster turnover | ${STATS.speed.baseCost} | x${STATS.speed.growth} | ${STATS.speed.surge} | ${STATS.speed.max} | +${BALANCE.speedStep * 100}% of base speed (session time = base / (1 + 0.02 x level)) |`);
p();
p('What that means, in words:');
{
  const r = ZONES[0];
  const ratio = (st: StatId, n: number) => statCost(r, st, n) / statCost(r, st, 0);
  p(`* **Level up** is the cheap, long ladder: cost grows only ${((STATS.price.growth - 1) * 100).toFixed(0)}% per level (level 100 costs ${f(ratio('price', 100))}x the first level, level 1000 ${f(ratio('price', 999))}x) while every level adds the same flat +5% of the base price. It is the "always something to buy" engine of the game and the only stat with a deep ladder (max 1000) and milestone bonuses.`);
  p(`* **Bigger class** costs **x${STATS.capacity.growth} per level** (plus a small surge): level 10 costs ${f(ratio('capacity', 10))}x the first level, level 25 ${f(ratio('capacity', 25))}x. One more guest is worth 1/(baseGuests + capacity) of the income, so the very first one is the best deal in the game (+33% on 3 guests) and every next one is dearer *and* worth less. Realistically a player buys a couple of dozen per zone, and only once the coins are huge (the bot ends with 13-30).`);
  p(`* **Faster turnover** compounds x${STATS.speed.growth} per level with a surge of ${STATS.speed.surge} per level on top (level 50 costs ${f(ratio('speed', 50))}x the first level, level 100 ${f(ratio('speed', 100))}x). Its base cost (${STATS.speed.baseCost}) is the highest, so it is the last of the three to be worth buying early, but each level is +2% of base speed forever and it reaches a **hard cap at level ${STATS.speed.max}: sessions take 1/${1 + BALANCE.speedStep * STATS.speed.max} of the base time (x${1 + BALANCE.speedStep * STATS.speed.max} faster)**. The bot maxes it in every zone.`);
}
p();
p('### Level-up milestones (bonus multiplier on the income of that zone)');
p('| at Level up level | multiplier | cumulative |');
p('|---|---|---|');
for (const [l, x] of LEVEL_MILESTONES) p(`| ${l} | x${x} | x${milestoneMult(l)} |`);
p();
p(`After level 300 every further 100 levels **doubles** the income (from level 400: x2^(floor(level/100) - 3)). Level 1000 is worth x${milestoneMult(1000)} in total. These jumps are why Level up stays worth buying deep into the game even though its plain gain per level shrinks.`);
p();
p('### Other costs');
p('```');
p('manager        = managerCost(60) x costScale^tier x (1 - discount)                (one-off, keeps the zone running by itself)');
p('facility(lvl)  = baseCost x growth^level x (1 - discount)                          (shared beach buildings, section 5)');
p('unlock coins   = round-to-2-significant-digits( factor x unlockMult(3) x costScale^tier )   (levels 2-4 and the sports)');
p('```');
p('Level 2/3/4 of a sport also need **12 / 30 / 60 upgrade levels** bought on the level before it (the sum of all three stats, `upgradeCount`). A new sport needs Level 2 of the sport before it plus coins.');
p();
p('### Worked example (Wave surfing, Beginner class, tier 0)');
{
  const ref = ZONES[0];
  const a = stats(ref, ZERO);
  const b = stats(ref, { capacity: 2, price: 10, speed: 5 });
  p(`Start: ${a.guests} guests x ${f(a.pricePerGuest)} coins = **${f(a.income)}** per session, ${t(a.duration)} per session = **${f(a.perSecond)} coins/s**.`);
  p(`After 2 Bigger class, 10 Level up, 5 Faster turnover (cost ${f(costOf(ref, 'capacity', 0, 2) + costOf(ref, 'price', 0, 10) + costOf(ref, 'speed', 0, 5))} coins in total): guests = 3 + 2 = ${b.guests}; price per guest = 5^0 x (1 + 0.05 x 10) = ${f(b.pricePerGuest)}; session = 6 / (1 + 0.02 x 5) = ${t(b.duration)}; income = ${b.guests} x ${f(b.pricePerGuest)} = ${f(b.income)}; **${f(b.perSecond)} coins/s** (${(b.perSecond / a.perSecond).toFixed(2)}x the start).`);
}
p();

// ---------------------------------------------------------------- 2
p('## 2. Progression rules that make the numbers matter');
p();
p('* Sports and levels get **more expensive by tier** (`costScale^tier`) but also **earn more** (`tierScale^tier`). A tier is a "rung" of the whole game; every zone has one (0 for Beginner class up to 11.8 for the Offshore regatta).');
p('* **Expansion 1 and 2** need Level 4 of every sport in the open areas and reset coins, zones, upgrades and beach buildings, but give **income x' + EXPANSION_MULT + ' each, for good**, and open the next area (Sea, then Ocean). Skills stay. Expansions no longer pay skill points (gems come from quests only).');
p('```');
for (const e of EXPANSIONS) p(`expansion ${e.n}: opens ${e.opens}, needs Level ${e.level} of every open sport, costs ${f(e.coins)} coins, income x${EXPANSION_MULT}`);
p('```');
p('* The **balance bot** (`scripts/simulate.ts`, an active but patient player who taps every waiting zone and always buys the best payback) is the referee. Target: the whole game in roughly 4-14 hours. Whenever a number in this document changes, re-run it.');
p();

// ---------------------------------------------------------------- 3
p('## 3. Per sport');
p();
p('Every sport uses exactly the same formulas. What makes a sport different is its data: which **tier** its four levels sit on (how much they earn and cost), its **base guests** and **base session time**, and how it is unlocked. The tables show, per zone, what each stat is worth on its own (the other two at 0) so the shape of each ladder is visible. **Payback** (in the "best buy" tables) = cost of the next level / extra coins per second that level gives = how long the purchase takes to earn itself back.');
p();
for (const sport of SPORTS) {
  p(`### ${sport.name}`);
  p();
  const first = sport.levels[0];
  p(`Area **${sport.area}**. ${sport.unlock ? `Unlock: own **Level ${sport.unlock.level} of ${SPORTS.find((x) => x.id === sport.unlock!.after)!.name}** and pay **${f(sport.unlock.coins)}** coins (after the beach expansion that opens its area it is open from the start).` : 'Open from the start.'} The four levels sit on tiers ${sport.levels.map((l) => l.tier).join(' / ')}: each next level earns ${f(tierFactor(sport.levels[1].tier - sport.levels[0].tier))}x and costs ${f(costFactor(sport.levels[1].tier - sport.levels[0].tier))}x per tier step of the first gap.`);
  p();
  p('| zone | tier | guests x sec | income/session | coins/s at start | manager | unlock coins | needs upgrades on previous level | coins/s with 10 cap, 50 price, 25 speed | its cost |');
  p('|---|---|---|---|---|---|---|---|---|---|');
  sport.levels.forEach((l, i) => {
    const ref = ZONES.find((z) => z.id === `${sport.id}-${i + 1}`)!;
    const a = stats(ref, ZERO);
    const mid: Lv = { capacity: 10, price: 50, speed: 25 };
    const b = stats(ref, mid);
    const cost = costOf(ref, 'capacity', 0, mid.capacity) + costOf(ref, 'price', 0, mid.price) + costOf(ref, 'speed', 0, mid.speed);
    p(`| ${l.name} (${ref.id}) | ${l.tier} | ${l.baseGuests} x ${l.baseSeconds}s | ${f(a.income)} | ${f(a.perSecond)} | ${f(managerCost(ref))} | ${l.unlock ? f(l.unlock.coins) : i === 0 && sport.unlock ? f(sport.unlock.coins) : 'free'} | ${l.unlock?.prevLevelUpgrades ?? '-'} | ${f(b.perSecond)} | ${f(cost)} |`);
  });
  p();
  const r0 = ZONES.find((z) => z.id === `${sport.id}-1`)!;
  const best = STAT_IDS.map((s) => {
    const a = stats(r0, ZERO);
    const b = stats(r0, withStat(s, 1));
    return { s, pay: statCost(r0, s, 0) / (b.perSecond - a.perSecond) };
  }).sort((x, y) => x.pay - y.pay);
  p(`First buy in ${first.name}: ${best.map((b) => `${STATS[b.s].label} pays back in ${t(b.pay)}`).join(', ')}. So the opening move is **${STATS[best[0].s].label}**.`);
  p();
  for (let i = 0; i < sport.levels.length; i++) {
    const ref = ZONES.find((z) => z.id === `${sport.id}-${i + 1}`)!;
    const l = sport.levels[i];
    p(`#### ${sport.name}, level ${i + 1}: ${l.name} (tier ${l.tier})`);
    p();
    p(`Base ${l.baseGuests} guests, ${l.baseSeconds} s, tierScale^${l.tier} = ${f(tierFactor(l.tier))} coins per guest, cost factor costScale^${l.tier} = ${f(costFactor(l.tier))}. One stat at a time (the other two at 0, so this shows the *shape* of each ladder):`);
    p();
    p('| stat | level | total cost so far | cost of next level | income/session | session time | coins/s | next level adds |');
    p('|---|---|---|---|---|---|---|---|');
    for (const s of STAT_IDS) {
      for (const n of CHECK[s]) {
        if (n > STATS[s].max) continue;
        const cur = stats(ref, withStat(s, n));
        const nxt = stats(ref, withStat(s, n + 1));
        const next = statCost(ref, s, n);
        p(`| ${LABEL[s]} | ${n} | ${f(costOf(ref, s, 0, n))} | ${f(next)} | ${f(cur.income)} | ${t(cur.duration)} | ${f(cur.perSecond)} | ${isFinite(next) ? `+${((nxt.perSecond / cur.perSecond - 1) * 100).toFixed(1)}%` : 'max'} |`);
      }
    }
    p();
    {
      const build: Lv = { capacity: 10, price: 100, speed: 25 };
      const base = stats(ref, build);
      p(`**Which buy is best right now?** In a typical mid-build (Bigger class 10, Level up 100, Faster 25: ${f(base.perSecond)} coins/s, ${f(costOf(ref, 'capacity', 0, 10) + costOf(ref, 'price', 0, 100) + costOf(ref, 'speed', 0, 25))} coins invested), one more level of each:`);
      p();
      p('| stat | cost | coins/s after | gain | payback |');
      p('|---|---|---|---|---|');
      for (const s of STAT_IDS) {
        const after = stats(ref, { ...build, [s]: build[s] + 1 });
        const c = statCost(ref, s, build[s]);
        p(`| ${LABEL[s]} | ${f(c)} | ${f(after.perSecond)} | +${((after.perSecond / base.perSecond - 1) * 100).toFixed(1)}% | ${t(c / (after.perSecond - base.perSecond))} |`);
      }
      p();
    }
    const all: Lv = { capacity: STATS.capacity.max, price: STATS.price.max, speed: STATS.speed.max };
    const mx = stats(ref, all);
    p(`Everything maxed (100 / 1000 / 100): ${mx.guests} guests x ${f(mx.pricePerGuest)} = ${f(mx.income)} per ${t(mx.duration)} = **${f(mx.perSecond)} coins/s**, for ${f(costOf(ref, 'capacity', 0, 100) + costOf(ref, 'price', 0, 1000) + costOf(ref, 'speed', 0, 100))} coins of upgrades. (For comparison the bot ends the game with about 13-30 capacity, 400-1000 price and ~100 speed per zone.)`);
    p();
  }
}

// ---------------------------------------------------------------- 4
p('## 4. Reading the ladders: what to look for when tuning');
p();
p('Payback time of the next upgrade is the number that shapes how the game *feels*: short paybacks (seconds to a minute) keep the player tapping; long ones (hours) mean it is time for the next zone/sport/expansion. The rules of thumb the current numbers follow:');
p('* **Early**: Level up pays back in seconds, Bigger class in tens of seconds, Faster turnover in minutes. All three feel worth buying.');
p(`* **The gap between Level up and the others is deliberate**: Level up ${STATS.price.growth}x per level vs Bigger class ${STATS.capacity.growth}x and Faster ${STATS.speed.growth}x + surge. Level up is the "always something to buy" engine; the other two are occasional bigger steps.`);
p(`* **Milestones create a rhythm**: right before level 25/50/75/100/200/300 the payback of Level up looks bad, right after the multiplier lands it looks great. The bot (and a good player) buys straight through those.`);
p(`* **Tier gap**: the cost of a new zone grows ${BALANCE.costScale}x per tier while its income grows ${BALANCE.tierScale}x, and a zone's own upgrades cost ${BALANCE.costScale}x more too. A brand-new higher-tier zone is therefore always a better investment than pushing an old zone's expensive tail, which is why the bot alternates between "unlock the next thing" and "top up".`);
p();

// ---------------------------------------------------------------- 5
p('## 5. Multipliers that sit on top (they multiply the numbers above)');
p();
p('```');
p('coinMultiplier = 3^expansions x (1 + skill allCoins) x adBoost(2 while active) x coinsX5(5 if bought) x surfClub(2 if subscribed) x product over beach buildings (1 + perLevel x (1 + skill facilityPower) x level)');
p('speedMultiplier = product over beach buildings that affect speed (1 + perLevel x level)');
p('```');
p('Skills also add per sport: +% coins, +% speed, +guests, -% upgrade cost (capped at 70% total), -% manager cost, -% unlock cost. Away time earns for 2 hours (plus skills and the Club).');
p();
p('| beach building | effect | per level | max level | base cost | growth |');
p('|---|---|---|---|---|---|');
for (const b of FACILITIES) p(`| ${b.name} | ${b.effect} | +${b.perLevel * 100}% | ${b.max} | ${f(b.baseCost)} | x${b.growth} |`);
p();
p('A fully built beach (all four buildings at level 8) gives about x' + (FACILITIES.filter((b) => b.effect === 'coins').reduce((m, b) => m * (1 + b.perLevel * b.max), 1)).toFixed(2) + ' coins and x' + (FACILITIES.filter((b) => b.effect === 'speed').reduce((m, b) => m * (1 + b.perLevel * b.max), 1)).toFixed(2) + ' speed on every sport at once.');
p();

// ---------------------------------------------------------------- 6
p('## 6. What the balance bot does with all this (pacing check)');
p();
const res = simulate({ maxSeconds: 16 * 3600, step: 2 });
const ft = (s: number) => `${Math.floor(s / 3600)}h${String(Math.floor((s % 3600) / 60)).padStart(2, '0')}m`;
p('Timeline of the active, patient bot (unlocks and expansions only; managers are bought in between):');
p();
p('| time | event |');
p('|---|---|');
for (const e of res.events) if (!e.what.endsWith('manager')) p(`| ${ft(e.t)} | ${e.what} |`);
p();
p(`Finished (everything unlocked and managed): **${res.finishedAt ? ft(res.finishedAt) : 'not within 16 h'}**, longest wait between purchases ${ft(res.longestWait.seconds)}, ${res.purchases} purchases. A relaxed player who only checks in now and then takes several times longer; away time (2 h, more with skills) and ads speed that up.`);
p();
p('## 7. What the numbers imply (worth knowing when tuning)');
p();
{
  const r = ZONES[0];
  const reach = (limit: number, st: StatId) => {
    let n = 0;
    while (n < STATS[st].max && costOf(r, st, 0, n + 1) <= limit) n++;
    return n;
  };
  p(`* **Bigger class has a decorative maximum.** It is capped at ${STATS.capacity.max} but, at x${STATS.capacity.growth} per level, the total cost of level 30 in the first zone is already ${f(costOf(r, 'capacity', 0, 30))} and of level 100 ${f(costOf(r, 'capacity', 0, 100))}. With 1 trillion coins to spend on it in a tier-0 zone a player reaches level ${reach(1e12, 'capacity')}; with 1 quadrillion, level ${reach(1e15, 'capacity')}. Higher tiers cost costScale^tier more, so their cap is lower still. (A Bigger class of 20-30 is the real ceiling; that is what the bot reaches.)`);
  p(`* **Level up is the workhorse.** Its cost only rises ${((STATS.price.growth - 1) * 100).toFixed(0)}% per level, so the 1000-level ladder is reachable (total ${f(costOf(r, 'price', 0, 1000))} in tier 0) and the milestones (x${milestoneMult(1000)} in total at level 1000) reward it. The bot ends near 400-1000 Level ups per zone.`);
  p(`* **Faster turnover is a fixed, finite bonus** (x${1 + BALANCE.speedStep * STATS.speed.max} at level ${STATS.speed.max}, total ${f(costOf(r, 'speed', 0, 100))} in tier 0). Because it multiplies everything else it is worth buying, but it is capped, so it can never run away.`);
  p(`* **Per-zone income at the end (all three maxed, tier 0 vs the last zone):** ${f(stats(ZONES[0], { capacity: 100, price: 1000, speed: 100 }).perSecond)} coins/s vs ${f(stats(ZONES[ZONES.length - 1], { capacity: 100, price: 1000, speed: 100 }).perSecond)} coins/s, before any expansion (x${EXPANSION_MULT} each), skill or building multiplier.`);
}
p();
p('---');
p('*Change `src/config/balance.ts`, `sports.ts` or `expansions.ts`, then run `npm run docs:economy` and `npx tsx scripts/simulate.ts` to see what moved.*');

writeFileSync(new URL('../docs/ECONOMY.md', import.meta.url), out.join('\n') + '\n');
console.log(`docs/ECONOMY.md written (${out.length} lines)`);
