export default async ({ page, shot, base }) => {
  await page.goto(base);
  await page.waitForTimeout(1500);
  await shot('start');
  await page.click('.zone-chip', { force: true });
  await page.waitForTimeout(3500);
  await shot('running');
  await page.evaluate(() => { window.__surf.game.state.coins = 500; });
  await page.waitForTimeout(6000);
  await shot('ready');
  await page.click('.zone-chip', { force: true });
  await page.waitForTimeout(1200);
  await shot('collected');
  await page.evaluate(() => window.__surf.ui.openZone('wave-1'));
  await page.waitForTimeout(1500);
  await shot('sheet');
  await page.click('[data-buy="capacity"]', { force: true });
  await page.click('[data-buy="price"]', { force: true });
  await page.click('[data-buy="manager"]', { force: true });
  await page.waitForTimeout(800);
  await shot('sheet-bought');
  await page.click('[data-close]', { force: true });
  await page.waitForTimeout(600);
  await page.evaluate(() => { window.__surf.game.state.coins = 5000; window.__surf.ui.openBeach(); });
  await page.waitForTimeout(800);
  await page.click('[data-buyfac="shop"]', { force: true });
  await page.click('[data-buyfac="cafe"]', { force: true });
  await page.waitForTimeout(1200);
  await shot('beach');
  await page.click('[data-close]', { force: true });
  await page.waitForTimeout(1500);
  await shot('back');
};
