export default async ({ page, shot, base }) => {
  const ev = (fn, a) => page.evaluate(fn, a);
  await page.goto(base);
  await page.waitForTimeout(1800);
  await ev(() => { const s = window.__surf.game.state; s.coins = 1e7; s.reputation = 30; });
  await ev(() => window.__surf.ui.openZone('wave-1'));
  await page.waitForTimeout(900);
  const rows = await ev(() => [...document.querySelectorAll('.sheet .up b')].map((b) => b.textContent.trim().replace(/\s+/g, ' ')));
  console.log('row order:', rows.join(' | '));
  await page.click('[data-mode="100"]', { force: true });
  await ev(() => { window.__surf.game.state.coins = 50; });
  await page.waitForTimeout(400);
  await shot('01-x100-unaffordable');
  await ev(() => { window.__surf.game.state.coins = 1e7; });
  await page.click('[data-mode="1"]', { force: true });
  const btn = await page.locator('[data-buy=price]').boundingBox();
  const before = await ev(() => window.__surf.game.state.zones['wave-1'].price);
  await page.mouse.move(btn.x + btn.width / 2, btn.y + btn.height / 2);
  await page.mouse.down();
  await page.waitForTimeout(600);
  const t1 = await ev(() => window.__surf.game.state.zones['wave-1'].price);
  await page.waitForTimeout(1500);
  const t2 = await ev(() => window.__surf.game.state.zones['wave-1'].price);
  await page.mouse.up();
  await page.waitForTimeout(300);
  const after = await ev(() => window.__surf.game.state.zones['wave-1'].price);
  await page.waitForTimeout(600);
  const still = await ev(() => window.__surf.game.state.zones['wave-1'].price);
  console.log('hold: start', before, 'after 0.6s', t1, 'after 2.1s', t2, 'released', after, 'later', still);
  await shot('02-after-hold');
  await ev(() => window.__surf.ui.closeSheet());
  await page.waitForTimeout(700);
  await page.click('[data-ref=beach]', { force: true });
  await page.waitForTimeout(900);
  await shot('03-beach');
  await ev(() => window.__surf.ui.openSports());
  await page.waitForTimeout(700);
  await shot('04-sports');
  await ev(() => window.__surf.ui.closeSheet());
  await page.waitForTimeout(700);
  await page.click('[data-ref=gear]', { force: true });
  await page.waitForTimeout(500);
  await shot('05-menu');
};
